### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by sokratis12GR** [sokratis12GR/ArmorPlus#63]
_Can you please translate ArmorPlus into your language?_

The language files are here:
https://github.com/TheDragonTeam/ArmorPlus/tree/1.12/src/main/resources/assets/armorplus/lang

Missing Language files:
language_file.lang contributors #PRs
- [X]  ar_sa.lang ImmortalPharaoh7 #18 , #23 
- [X]  bg_bg .lang
- [ ]  cs_cz.lang
- [X]  de_de.lang LuminousLizard, Moritz30 #3 , #5 , #6 , #9 , #16, #49
- [X]  el_gr.lang Tasomanya 
- [ ]  en_au.lang
- [x]  en_pt.lang
- [X]  en_us.lang 
- [X]  es_es.lang SatanicSanta #1 , #2 , #4 , #8
- [ ]  fi_fi.lang
- [X]  fr_fr.lang ImmortalPharaoh7 #20 , #21 , #60 , [Commit 1](https://github.com/TheDragonTeam/ArmorPlus/commit/0c107d31262aa2c93c32f071beddcaf8448986c4) , [Commit 2](https://github.com/TheDragonTeam/ArmorPlus/commit/febf882cb72cc60946d957e8c607734d102b9511) , [Commit 3](https://github.com/TheDragonTeam/ArmorPlus/commit/321041855447651afae65d9888ca9c8315b212f9) , [Commit 4](https://github.com/TheDragonTeam/ArmorPlus/commit/072cba31480c1e5bda80cd498cc21078ea6281a6)
- [ ]  he_il.lang
- [ ]  hu_hu.lang
- [ ]  it_it.lang
- [X]  ja_jp.lang ikunai #68
- [ ]  ko_kr.lang
- [ ]  lb_lu.lang
- [ ]  lol_us.lang
- [ ]  nb_no.lang
- [ ]  nl_nl.lang
- [ ]  pl_pl.lang
- [ ]  pt_br.lang
- [X] pt_pt.lang KewaiiGamer [Commit 1](https://github.com/TheDragonTeam/ArmorPlus/commit/6be501b95591465b4c0823cd2f77a5cfcb05f1bc) , [Commit 2](https://github.com/TheDragonTeam/ArmorPlus/commit/3b64686d908114dfd053364d06a2121e115c0989)
- [X]  ru_ru.lang FTB_lag [Commit](https://github.com/TheDragonTeam/ArmorPlus/commit/5756684e32e20f99794f8db3600962a1bed782d6)
- [ ]  sv_se.lang
- [ ]  uk_ua.lang
- [X]  zh_cn.lang 3TUSK #10 , #31
- [ ]  zh_tw.lang

**Comment by ikunai** [comment]
I am prepared to carry out the Japanese localization.
Please In addition to the Contributor.

**Comment by ikunai** [comment]
I made the PR.
https://github.com/TheDragonTeam/ArmorPlus/pull/68
